### ISSUE TITLE
unexpected FileNotFoundException during run from command line

### ISSUE THREAD

**Issue by romani** [CodeNarc/CodeNarc#187]
```
$ ls
CodeNarc-0.26.0.jar  groovy-all-2.4.3.jar  log4j-1.2.14.jar  StarterRuleSet-AllRulesByCategory.groovy.txt

$ pwd
/var/tmp/codenarc

$ file /var/tmp/codenarc/StarterRuleSet-AllRulesByCategory.groovy.txt
/var/tmp/codenarc/StarterRuleSet-AllRulesByCategory.groovy.txt: Python script, ASCII text executable

$ java -classpath groovy-all-2.4.3.jar:CodeNarc-0.26.0.jar:log4j-1.2.14.jar org.codenarc.CodeNarc -basedir=my-groovy -rulesetfiles=/var/tmp/codenarc/StarterRuleSet-AllRulesByCategory.groovy.txt -report=console
log4j:WARN No appenders could be found for logger (org.codenarc.ruleregistry.PropertiesFileRuleRegistry).
log4j:WARN Please initialize the log4j system properly.
ERROR: File [/var/tmp/codenarc/StarterRuleSet-AllRulesByCategory.groovy.txt] does not exist or is not accessible
java.io.FileNotFoundException: File [/var/tmp/codenarc/StarterRuleSet-AllRulesByCategory.groovy.txt] does not exist or is not accessible
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
	at org.codenarc.util.io.ClassPathResource.getInputStream(ClassPathResource.groovy:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:73)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:82)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:293)
	at org.codenarc.ruleset.GroovyDslRuleSet.evaluateDsl(GroovyDslRuleSet.groovy:62)
	at org.codenarc.ruleset.GroovyDslRuleSet.this$2$evaluateDsl(GroovyDslRuleSet.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:163)
	at org.codenarc.ruleset.GroovyDslRuleSet.<init>(GroovyDslRuleSet.groovy:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
	at org.codenarc.ruleset.RuleSetUtil.loadRuleSetFile(RuleSetUtil.groovy:40)
	at org.codenarc.ruleset.RuleSetUtil$loadRuleSetFile.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
	at org.codenarc.CodeNarcRunner$_createRuleSet_closure2.doCall(CodeNarcRunner.groovy:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2027)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2012)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2053)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
	at org.codenarc.CodeNarcRunner.createRuleSet(CodeNarcRunner.groovy:98)
	at org.codenarc.CodeNarcRunner.execute(CodeNarcRunner.groovy:69)
	at org.codenarc.CodeNarcRunner$execute.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
	at org.codenarc.CodeNarc.execute(CodeNarc.groovy:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
	at org.codenarc.CodeNarc.main(CodeNarc.groovy:111)
CodeNarc - static analysis for Groovy',
Usage: java org.codenarc.CodeNarc [OPTIONS]
  where OPTIONS are zero or more command-line options of the form "-NAME[=VALUE]":
    -basedir=<DIR>
        The base (root) directory for the source code to be analyzed.
        Defaults to the current directory (".").
    -includes=<PATTERNS>
        The comma-separated list of Ant-style file patterns specifying files that must
        be included. Defaults to "**/*.groovy".
    -excludes=<PATTERNS>
        The comma-separated list of Ant-style file patterns specifying files that must
        be excluded. No files are excluded when omitted.
    -rulesetfiles=<FILENAMES>
        The path to the Groovy or XML RuleSet definition files, relative to the classpath.
        This can be a single file path, or multiple paths separated by commas.
        Defaults to "rulesets/basic.xml"
    -title=<REPORT TITLE>
        The title descriptive for this analysis; used in the output report(s). Optional.
    -report=<REPORT-TYPE[:FILENAME]>
        The definition of the report to produce. The option value is of the form
        TYPE[:FILENAME], where TYPE is "html", "text", "xml", or "console" and FILENAME is the filename (with
        optional path) of the output report filename. If the report filename is
        omitted, the default filename is used for the specified report type
        ("CodeNarcReport.html" for "html" and "CodeNarcXmlReport.xml" for "xml"). If no
        report option is specified, default to a single "html" report with the
        default filename.
    -help
        Display the command-line help. If present, this must be the only command-line parameter.
  Example command-line invocations:
    java org.codenarc.CodeNarc
    java org.codenarc.CodeNarc -rulesetfiles="rulesets/basic.xml" title="My Project"
    java org.codenarc.CodeNarc -report=xml:MyXmlReport.xml -report=html
    java org.codenarc.CodeNarc -help'
```

**Comment by chrismair** [comment]
I apologize for the late response.

The _-rulesetfiles_ option specifies filename(s) relative to the classpath, not to the filesystem.

**Comment by romani** [comment]
@chrismair , is there  a way to define path to filesystem ?

**Comment by chrismair** [comment]
You should be able to add "/var/tmp/codenarc" to the classpath and just set **-rulesetfiles=StarterRuleSet-AllRulesByCategory.groovy.txt**.

**Comment by romani** [comment]
yes, it works.

```
/var/tmp/codenarc$ ll
total 11396
drwxrwxr-x  3 user user    4096 Mar 18 13:36 ./
drwxrwxrwt 28 root    root       4096 Mar 18 13:38 ../
-rw-rw-r--  1 user user 4300379 Mar 18 12:17 CodeNarc-0.27.0.jar
-rw-rw-r--  1 user user 6969675 Mar 18 12:28 groovy-all-2.4.3.jar
-rw-rw-r--  1 user user  367444 Mar 18 12:18 log4j-1.2.14.jar
drwxrwxr-x  2 user user    4096 Mar 18 13:36 my-groovy/
-rw-rw-r--  1 user user   10597 Mar 18 12:19 StarterRuleSet-AllRulesByCategory.groovy.txt

/var/tmp/codenarc$ java -classpath groovy-all-2.4.3.jar:CodeNarc-0.27.0.jar:log4j-1.2.14.jar:/var/tmp/codenarc org.codenarc.CodeNarc -basedir=my-groovy -rulesetfiles=StarterRuleSet-AllRulesByCategory.groovy.txt -report=console
log4j:WARN No appenders could be found for logger (org.codenarc.ruleregistry.PropertiesFileRuleRegistry).
log4j:WARN Please initialize the log4j system properly.
CodeNarc Report - Mar 18, 2017 1:38:51 PM

Summary: TotalFiles=0 FilesWithViolations=0 P1=0 P2=0 P3=0

[CodeNarc (http://www.codenarc.org) v0.27.0]
CodeNarc completed: (p1=0; p2=0; p3=0) 1901ms

```

certain file can not be added to classpath, as it will be ignored - http://docs.oracle.com/javase/7/docs/technotes/tools/windows/classpath.html

**Comment by erdi** [comment]
For what it's worth, you could also prefix your absolute ruleset file path with `file:` and then you won't need to add any directories to the classpath.

**Comment by romani** [comment]
thanks a lot, yes it works:
` java -classpath groovy-all-2.4.3.jar:CodeNarc-0.27.0.jar:log4j-1.2.14.jar org.codenarc.CodeNarc -basedir=my-groovy -rulesetfiles=file:///var/tmp/codenarc/StarterRuleSet-AllRulesByCategory.groovy.txt -report=console`

```
/var/tmp/codenarc$ java -classpath groovy-all-2.4.3.jar:CodeNarc-0.27.0.jar:log4j-1.2.14.jar org.codenarc.CodeNarc -basedir=my-groovy -rulesetfiles=file:///var/tmp/codenarc/StarterRuleSet-AllRulesByCategory.groovy.txt -report=console
log4j:WARN No appenders could be found for logger (org.codenarc.ruleregistry.PropertiesFileRuleRegistry).
log4j:WARN Please initialize the log4j system properly.
CodeNarc Report - Mar 18, 2017 2:49:54 PM

Summary: TotalFiles=0 FilesWithViolations=0 P1=0 P2=0 P3=0

[CodeNarc (http://www.codenarc.org) v0.27.0]
CodeNarc completed: (p1=0; p2=0; p3=0) 1862ms
```
