### ISSUE TITLE
java.util.regex.PatternSyntaxException from TrailingWhitespaceRule

### ISSUE THREAD

**Issue by epkaxma** [CodeNarc/CodeNarc#307]
Hi,
Tried 1.1 but I get 
ERROR: Illegal/unsupported escape sequence near index 13
[^\n]*[ \t]+\R
             ^
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 13
[^\n]*[ \t]+\R
             ^
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.escape(Unknown Source)
	at java.util.regex.Pattern.atom(Unknown Source)
	at java.util.regex.Pattern.sequence(Unknown Source)
	at java.util.regex.Pattern.expr(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at org.codehaus.groovy.runtime.InvokerHelper.findRegex(InvokerHelper.java:333)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.findRegex(ScriptBytecodeAdapter.java:766)
	at org.codenarc.rule.formatting.TrailingWhitespaceRule.applyTo(TrailingWhitespaceRule.groovy:33)
	at org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:143)
	at org.codenarc.rule.Rule$applyTo.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codenarc.rule.Rule$applyTo.call(Unknown Source)
...
on my linux. Removed the class file from the jar as a workaround.

**Comment by chrismair** [comment]
Hmmm, that is weird and unexpected. I am using CodeNarc 1.1, and that rule, on both Windows and Linux with no problems.

I would expect you could also just disable/remove that rule from your ruleset as a workaround.

**Comment by chrismair** [comment]
Okay, I think I see the problem. I unintentionally introduced a Java 1.8 dependency using that **\R** matcher. Sigh.

**Comment by chrismair** [comment]
Fixed for next release. Removed Java 1.8 dependency.
