### ISSUE TITLE
NullPointerException during declaration null variable.

### ISSUE THREAD

**Issue by valery93** [CodeNarc/CodeNarc#322]
Hello

Codenarc throws NullPointerException when I declare a variable in this way:
`public static final SomeObject SOME_NULL_VALUE = null`

Stacktrace:
```
Error from [org.codenarc.rule.security.UnsafeArrayDeclarationRule] processing source file [/SomeClass.groovy]
java.lang.NullPointerException
        at org.codenarc.util.AstUtil.getFieldType(AstUtil.java:991)
        at org.codenarc.util.AstUtil$getFieldType$129.call(Unknown Source)
        at org.codenarc.rule.security.UnsafeArrayDeclarationAstVisitor.isArray(UnsafeArrayDeclarationRule.groovy:45)
```

My setup:
Codenarc 1.0
Spock b0f30cf3
Groovy 2.4.12
Gradle 4.2.1

**Comment by dabrowt1** [comment]
Also experiencing this, and it is very annoying.
