### ISSUE TITLE
Indentation rule with Spock labels: MissingPropertyException: No such property: expression

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#355]
From #345.

Code with (Spock) labels on an if statement:
````
void 'androidLint is run'() {
        given:
        writeAndroidBuildFile(androidVersion)
        ...

        then:
        if (GradleVersion.version(version) >= GradleVersion.version('2.5')) {
            ....
        }
````

throw exception:
````
Error from [org.codenarc.rule.formatting.IndentationRule] processing source file [/Users/jmsotuyo/Documents/workspace/static-code-analysis-plugin/src/integTest/groovy/com/monits/gradle/sca/CpdIntegTest.groovy]
groovy.lang.MissingPropertyException: No such property: expression for class: org.codehaus.groovy.ast.stmt.IfStatement
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:51)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
        at org.codenarc.rule.formatting.IndentationAstVisitor.isSpockBlockLabel(IndentationRule.groovy:234)
        at org.codenarc.rule.formatting.IndentationAstVisitor.this$5$isSpockBlockLabel(IndentationRule.groovy)
````

**Comment by chrismair** [comment]
Available in CodeNarc 1.2.1
