### ISSUE TITLE
Error when name/path of ruleset file contains number sign (#)

### ISSUE THREAD

**Issue by grv87** [CodeNarc/CodeNarc#400]
`rulesetfiles` option accepts file paths with `file:` prefix.
However, there is a problem if path contains number sign (`#`).

Reproduced with:
OS: Windows
JDK: 8, 11
Groovy: 2.4.12, 2.5.2
CodeNarc: 1.0, 1.3

* If the part before `#` represents existing path, e.g.:
  * `file:..\codenarc-configFile-absolute-v2\#project\codenarc.xml`
  * `file:R:\codenarc-configFile-absolute-v2\#project\codenarc.xml`
 then there is an error:
```
ERROR: Content is not allowed in prolog.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:152)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
        at javax.xml.validation.Validator.validate(Validator.java:124)
        at javax.xml.validation.Validator$validate.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at org.codenarc.ruleset.XmlReaderRuleSet.validateXml(XmlReaderRuleSet.groovy:131)  
```
  In this case, the problematic 'xml' is not an actual ruleset file, but the list of dir entries of existing path.

* If the path before `#` doesn't exist:
  * `file:#code#narc.xml`
  * `file:#project\codenarc.xml`

  then error is:
```
java.io.FileNotFoundException:
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1045)
        at java_net_URL$openStream.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at org.codenarc.util.io.UrlResource.getInputStream(UrlResource.groovy:44)
```

It looks like the file path is interpreted as URI, and `#` starts a fragment and is not considered as a part of the file path/name.
If it should be escaped then I think this should be noted in documentation.

P.S.  Looking at `CodeNarcRunner` source, I see another problem. `ruleSetFiles` are split with `tokenize` and comma separator, and no built-in escaping for comma is assumed. I think this should be addressed too.

**Comment by chrismair** [comment]
I had to add some tests to make sure this would work, but you can optionally URL-encode the URI path(s) specified by *rulesetfiles*. That should address the problem of both '#' and ',' within a filename.
For instance, a *rulesetfiles* value of:
`file:src/test/resources/RuleSet-,#.txt`
can be encoded as:
`file:src%2Ftest%2Fresources%2FRuleSet-%2C%23.txt`

See `URLEncoder#encode(java.lang.String, java.lang.String)`.

I am adding information about that to the online documentation.
