### ISSUE TITLE
No such property: staticImportAliases using Groovy 3.0.0-beta-1

### ISSUE THREAD

**Issue by henrik242** [CodeNarc/CodeNarc#426]
Using Groovy 3.0.0-beta-1 and Spock 1.3-groovy-2.5-SNAPSHOT I get errors like these:
```
Error from [org.codenarc.rule.imports.UnusedImportRule] processing source file [/Users/me/src/app/shared/test-helpers/src/test/java/com/example/TestBuildPathsTest.groovy]
groovy.lang.MissingPropertyException: No such property: staticImportAliases for class: org.codehaus.groovy.ast.ModuleNode
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetPropertySafe(AbstractCallSite.java:416)
        at org.codenarc.rule.imports.UnusedImportRule.processStaticImports(UnusedImportRule.groovy:58)
        at org.codenarc.rule.imports.UnusedImportRule.this$3$processStaticImports(UnusedImportRule.groovy)
        at jdk.internal.reflect.GeneratedMethodAccessor1853.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at org.codenarc.rule.imports.UnusedImportRule.applyTo(UnusedImportRule.groovy:39)
        at org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:143)
        at org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
        at org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
        at org.codenarc.ant.AntFileSetSourceAnalyzer.processFile(AntFileSetSourceAnalyzer.java:171)
        at org.codenarc.ant.AntFileSetSourceAnalyzer.access$000(AntFileSetSourceAnalyzer.java:42)
        at org.codenarc.ant.AntFileSetSourceAnalyzer$1.run(AntFileSetSourceAnalyzer.java:160)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```
Ref. https://github.com/spockframework/spock/issues/997

**Comment by leonard84** [comment]
Try running without CodeNarc, it does not support Groovy 3 yet AFAIK.

**Comment by henrik242** [comment]
Codenarc stops complaining and seems to run well if I disable UnusedImportRule in the codenarc config.

**Comment by chrismair** [comment]
Okay, I see that there is still some leftover code checking for pre-Groovy 1.8 code (when the AST had some important differences). And the code that looks for that just checks if Groovy version is 2.x., and not 3.x!  So the above stack trace is going down that "old" code path. I will clean that up.
