### ISSUE TITLE
Error from [org.codenarc.rule.convention.HashtableIsObsoleteRule] processing source file [null]

### ISSUE THREAD

**Issue by CreeTar** [CodeNarc/CodeNarc#438]
Browsing files with CodeNarc Updates 4.2.1 on IntellIJ 2019.2 caused StackOverflow, can't really say which file the cause is since stacktrace is not helping I had 10 files opened:

```java.lang.StackOverflowError
	at org.codehaus.groovy.reflection.GroovyClassValuePreJava7.get(GroovyClassValuePreJava7.java:94)
	at org.codehaus.groovy.reflection.ClassInfo.getClassInfo(ClassInfo.java:144)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:258)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:883)
	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:34)
	at groovy.lang.Reference.<init>(Reference.java:37)
	at org.codenarc.util.WildcardPattern.matches(WildcardPattern.groovy)
	at org.codenarc.util.WildcardPattern$matches.call(Unknown Source)
	at org.codenarc.rule.ClassReferenceAstVisitor.checkNodeType(ClassReferenceAstVisitor.groovy:151)
	at org.codenarc.rule.ClassReferenceAstVisitor.this$5$checkNodeType(ClassReferenceAstVisitor.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor3209.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.codenarc.rule.ClassReferenceAstVisitor.visitCastExpression(ClassReferenceAstVisitor.groovy:123)
	at jdk.internal.reflect.GeneratedMethodAccessor3218.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

```
Following exceptions happened soon after this one, most probably they are induced.


2019-09-02T17:07:12.463
Error from [org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceRule] processing source file [null]
java.lang.StackOverflowError
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.nonParamCheck(PogoMetaMethodSite.java:83)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.checkCall(PogoMetaMethodSite.java:95)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceAstVisitor.visitCastExpression(UnnecessaryPackageReferenceRule.groovy:118)
	at jdk.internal.reflect.GeneratedMethodAccessor3218.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
...
```

**Comment by chrismair** [comment]
What do you mean by "Browsing files with CodeNarc Updates 4.2.1 on IntellIJ 2019.2"? Is that an IntelliJ IDEA CodeNarc plugin or something? How is that executing CodeNarc? What version of CodeNarc (because 4.2.1 is not a valid version)?

**Comment by CreeTar** [comment]
> What do you mean by "Browsing files with CodeNarc Updates 4.2.1 on IntellIJ 2019.2"? Is that an IntelliJ IDEA CodeNarc plugin or something? How is that executing CodeNarc? What version of CodeNarc (because 4.2.1 is not a valid version)?

I thought it was from you guys? https://plugins.jetbrains.com/plugin/12106-codenarc-updated
