### ISSUE TITLE
Getting error while running codenarc - ERROR: Lgroovy/text/TemplateEngine;

### ISSUE THREAD

**Issue by ramkumar-d** [CodeNarc/CodeNarc#449]
{C02Q1197G8WN:~/codenarc}$ ls -l
total 21304
-rw-r--r--@ 1 ramkumar  staff  4621969 Dec  9 16:14 CodeNarc-1.4.jar
-rw-r--r--  1 ramkumar  staff       68 Dec  9 17:35 codenarc.properties
-rw-r--r--  1 ramkumar  staff  5548387 Dec  9 16:51 groovy-2.5.8.jar
-rw-r--r--@ 1 ramkumar  staff    41203 Dec  9 16:51 slf4j-api-1.7.25.jar

{C02Q1197G8WN:~/codenarc}$ java -classpath groovy-2.5.8.jar:CodeNarc-1.4.jar:slf4j-api-1.7.25.jar org.codenarc.CodeNarc -basedir=/Users/ramkumar/SDF/groovy/jira-partner/lrms -rulesetfiles="file:/Users/ramkumar/codenarc/codenarc.properties" -report=console
ERROR: Lgroovy/text/TemplateEngine;
java.lang.NoClassDefFoundError: Lgroovy/text/TemplateEngine;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.codehaus.groovy.reflection.CachedClass$1$1.run(CachedClass.java:66)
	at org.codehaus.groovy.reflection.CachedClass$1$1.run(CachedClass.java:64)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:64)
	at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:59)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:50)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:37)
	at org.codehaus.groovy.reflection.CachedClass.getFields(CachedClass.java:303)
	at groovy.lang.MetaClassImpl.addFields(MetaClassImpl.java:2412)
	at groovy.lang.MetaClassImpl.inheritFields(MetaClassImpl.java:2407)
	at groovy.lang.MetaClassImpl.setupProperties(MetaClassImpl.java:2294)
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3366)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3331)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:287)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:329)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:272)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:969)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:86)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:241)
	at org.codenarc.report.ReportWriterFactory.getReportWriter(ReportWriterFactory.groovy:38)
	at org.codenarc.report.ReportWriterFactory$getReportWriter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.codenarc.CodeNarc.parseReport(CodeNarc.groovy:216)
	at org.codenarc.CodeNarc.this$2$parseReport(CodeNarc.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at org.codenarc.CodeNarc$_parseArgs_closure3.doCall(CodeNarc.groovy:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2136)
	at org.codehaus.groovy.runtime.dgm$181.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.codenarc.CodeNarc.parseArgs(CodeNarc.groovy:192)
	at org.codenarc.CodeNarc.execute(CodeNarc.groovy:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.codenarc.CodeNarc.main(CodeNarc.groovy:135)
Caused by: java.lang.ClassNotFoundException: groovy.text.TemplateEngine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 73 more
CodeNarc - static analysis for Groovy',
Usage: java org.codenarc.CodeNarc [OPTIONS]
  where OPTIONS are zero or more command-line options of the form "-NAME[=VALUE]":
    -basedir=<DIR>
        The base (root) directory for the source code to be analyzed.
        Defaults to the current directory (".").
    -includes=<PATTERNS>
        The comma-separated list of Ant-style file patterns specifying files that must
        be included. Defaults to "**/*.groovy".
    -excludes=<PATTERNS>
        The comma-separated list of Ant-style file patterns specifying files that must
        be excluded. No files are excluded when omitted.
    -rulesetfiles=<FILENAMES>
        The path to the Groovy or XML RuleSet definition files, relative to the classpath.
        This can be a single file path, or multiple paths separated by commas. Each path may be optionally prefixed by
        any of the valid java.net.URL prefixes, such as "file:" (to load from a relative or absolute filesystem path),
        or "http:". If it is a URL, its path may be optionally URL-encoded. That can be useful if the path contains
        any problematic characters, such as comma (',') or hash ('#'). For instance:
            file:src/test/resources/RuleSet-,#.txt
        can be encoded as:
            file:src%2Ftest%2Fresources%2FRuleSet-%2C%23.txt
        See URLEncoder#encode(java.lang.String, java.lang.String). Defaults to "rulesets/basic.xml"
    -maxPriority1Violations=<MAX>
        The maximum number of priority 1 violations allowed (int).
    -maxPriority2Violations=<MAX>
        The maximum number of priority 2 violations allowed (int).
    -maxPriority3Violations=<MAX>
        The maximum number of priority 3 violations allowed (int).
    -title=<REPORT TITLE>
        The title for this analysis; used in the output report(s), if supported by the report type. Optional.
    -report=<REPORT-TYPE[:FILENAME]>
        The definition of the report to produce. The option value is of the form
        TYPE[:FILENAME], where TYPE is "html", "text", "xml", or "console" and FILENAME is the filename (with
        optional path) of the output report filename. If the report filename is
        omitted, the default filename is used for the specified report type
        ("CodeNarcReport.html" for "html" and "CodeNarcXmlReport.xml" for "xml"). If no
        report option is specified, default to a single "html" report with the
        default filename.
    -help
        Display the command-line help. If present, this must be the only command-line parameter.
  Example command-line invocations:
    java org.codenarc.CodeNarc
    java org.codenarc.CodeNarc -rulesetfiles="rulesets/basic.xml" title="My Project"
    java org.codenarc.CodeNarc -report=xml:MyXmlReport.xml -report=html
    java org.codenarc.CodeNarc -help'

**Comment by chrismair** [comment]
It is missing the `gradle-templates` jar from the classpath. That is brought in by `groovy-ant`. So either use the `groovy-all` dependency or else add `groovy-ant` and `groovy-xml` explicitly.

**Comment by ramkumar-d** [comment]
Thanks, @chrismair. After using groovy-all.jar it started working fine.

**Comment by tmysik** [comment]
I am already using `groovy-all` but still getting this error. In my case, this helped:

```groovy
dependencies {
    [...]
    codenarc ("org.codenarc:CodeNarc:${codenarc.toolVersion}")
    codenarc('org.codehaus.groovy:groovy-templates')
}
```
