### ISSUE TITLE
[BUG] Formatting rule causes exception

### ISSUE THREAD

**Issue by rabits** [CodeNarc/CodeNarc#590]
Hello folks, found a weird behavior of `ClassStartsWithBlankLineAstVisitor.checkIfThereIsBlankLineAfterOpeningBrace` (and probably the others that uses `getLine(+1)`):
```
ERROR: java.lang.NullPointerException: Cannot invoke method trim() on null object
java.lang.NullPointerException: Cannot invoke method trim() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at java_lang_String$trim$0.call(Unknown Source)
	at org.codenarc.rule.formatting.ClassStartsWithBlankLineAstVisitor.checkIfThereIsBlankLineAfterOpeningBrace(ClassStartsWithBlankLineRule.groovy:108)
...
```

Added a couple of debugging lines (actually will be great to catch it on Rule side - which file is causing the exception to not recompile the package) and found the file:
```
...
@groovy.transform.InheritConstructors
class AppException extends Exception {}
```
so after the class there is no additional lines and it's becoming null. When I modified it to:
```
...
@groovy.transform.InheritConstructors
class AppException extends Exception {
}
```
it started to work fine.

**Comment by SergeyMormul** [comment]
Hello everyone! I have the same problem in an annotation class within version 2.1.0.
I have 
```
Error from [org.codenarc.rule.formatting.ClassStartsWithBlanLineRule] processing source file [...UnitTest.groovy]
java.lang.NullPointerException: Cannot invoke trim() on bull object
```
For the annotation class
```
@Target( ElementType.TYPE )
@Retention( RretentionPolicy.RUNTIME )
@Inherited
@interface UnitTest { }
```
The hotfix suggested by @rabits violates ClassEndsWithBlankLine. The NPE is trown regardles of a number of spaces between {}.

Configuration:
gradle: 6.8
groovy: 3.0.8
codenarc: 2.1.0

**Comment by chrismair** [comment]
Sorry, I should have replied earlier. Yes, opening the new issue #652 as you did is the right approach. Thanks.
