### ISSUE TITLE
A plenty of StackOverflowError which are difficult to diagnose

### ISSUE THREAD

**Issue by musketyr** [CodeNarc/CodeNarc#621]
Hi, I'm now maintaining https://github.com/melix/codenarc-idea. I have quite a lot of `StackOverflowError` which looks like they origin from the rules themselves not the plugin code.

The plugin uses Groovy 2.5.11, CodeNarc 2.1.0 and Java 11.0.10.

I can give you an access to the Sentry project where I collect the errors but there are the few of them:

```
java.lang.StackOverflowError: null
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at jdk.internal.reflect.GeneratedMethodAccessor4974.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.grails.GrailsMassAssignmentAstVisitor.visitConstructorCallExpression(GrailsMassAssignmentRule.groovy:50)
    at jdk.internal.reflect.GeneratedMethodAccessor4974.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.grails.GrailsMassAssignmentAstVisitor.visitConstructorCallExpression(GrailsMassAssignmentRule.groovy:50)
    at jdk.internal.reflect.GeneratedMethodAccessor4974.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
```

```
java.lang.StackOverflowError: null
    at jdk.internal.reflect.GeneratedMethodAccessor8856.invoke
    at org.codenarc.rule.basic.BitwiseOperatorInConditionalAstVisitor.visitTernaryExpression(BitwiseOperatorInConditionalRule.groovy:88)
    at jdk.internal.reflect.GeneratedMethodAccessor8745.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.basic.BitwiseOperatorInConditionalAstVisitor.visitTernaryExpression(BitwiseOperatorInConditionalRule.groovy:88)
    at jdk.internal.reflect.GeneratedMethodAccessor8745.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.basic.BitwiseOperatorInConditionalAstVisitor.visitTernaryExpression(BitwiseOperatorInConditionalRule.groovy:88)
```

```
java.lang.StackOverflowError: null
    at java.lang.Exception.<init>(Exception.java:102)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceAstVisitor.visitConstructorCallExpression(UnnecessaryPackageReferenceRule.groovy:79)
    at jdk.internal.reflect.GeneratedMethodAccessor4974.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceAstVisitor.visitConstructorCallExpression(UnnecessaryPackageReferenceRule.groovy:79)
    at jdk.internal.reflect.GeneratedMethodAccessor4974.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceAstVisitor.visitConstructorCallExpression(UnnecessaryPackageReferenceRule.groovy:79)
    at jdk.internal.reflect.GeneratedMethodAccessor4974.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceAstVisitor.visitConstructorCallExpression(UnnecessaryPackageReferenceRule.groovy:79)
    at jdk.internal.reflect.GeneratedMethodAccessor4974.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
    at org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceAstVisitor.visitConstructorCallExpression(UnnecessaryPackageReferenceRule.groovy:79)

```

Have you ever faced something similar?

**Comment by chrismair** [comment]
This does not look familiar. What is the Groovy code that is being analyzed that causes the above StackOverflowErrors? Does it just happen for specific Groovy code examples? Are these errors new with CodeNarc 2.1.0, and the same code caused no errors before?

**Comment by musketyr** [comment]
I'm trying to get the code but this is all I have. The SFO is difficult to catch with context.

**Comment by musketyr** [comment]
@chrismair I'm starting to suspect the Gradle build files or scrips in general.

**Comment by musketyr** [comment]
@paulk-asert @ danielsun1106 have you ever seen something similar? it seems to me that for some reason the `CachedMethod` points to a wrong method (from the class, not a superclass).

this happens in Groovy version `2.5.14`

**Comment by musketyr** [comment]
it resembles me a bit of https://issues.apache.org/jira/browse/GROOVY-4922

**Comment by chrismair** [comment]
If possible, can you check whether these problems still occur with Groovy 3.x? The next release of CodeNarc will require 3.x (3.0.9 for now), and that includes significant Groovy parser changes from 2.x.

**Comment by musketyr** [comment]
Thanks for an update @chrismair. I will check this next week once I get back from the vacations.

**Comment by musketyr** [comment]
There is not really a good way how to choose the Groovy version as the one from IntelliJ Groovy plugin dominates the build 
(via detached configurations from the IntelliJ Gradle plugin) but I'm trying to at least upgrade to the latest 2.5.x which is now supported by the latest releases.

**Comment by musketyr** [comment]
so it looked good for a couple of days but probably just because I was not working on many Groovy files. now it's back to normal with reporting couple of SFOs a day.

**Comment by pherold0923** [comment]
I see this as well in IntelliJ. Above the stack trace there is this:

Error from [org.codenarc.rule.jdbc.JdbcConnectionReferenceRule] processing source file [null]

java.lang.StackOverflowError
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)

Also induced
Error from [org.codenarc.rule.convention.VectorIsObsoleteRule] processing source file [null]

**Comment by musketyr** [comment]
small update - the latest version uses CodeNarc 2.2.0 and Groovy 3.0.9 and still generates the error above
