### ISSUE TITLE
Does not work on JDK 16

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#630]
Running CodeNarc on a project that uses JDK 16 and Gradle 7.0.2 leads to:

```
Error processing file: 'com/company/SomeSpec.groovy'; BUG! exception in phase 'semantic analysis' in source unit 'None' Unsupported class file major version 60
Error from [org.codenarc.rule.design.AbstractClassWithoutAbstractMethodRule] processing source file [/home/boris/project/src/test/groovy/com/company/SomeSpec.groovy]
BUG! exception in phase 'semantic analysis' in source unit 'None' Unsupported class file major version 60
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:969)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:642)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:591)
        at org.codehaus.groovy.control.CompilationUnit$compile$2.call(Unknown Source)
        at org.codenarc.source.AbstractSourceCode.init(AbstractSourceCode.groovy:98)
        at org.codenarc.source.AbstractSourceCode.getAst(AbstractSourceCode.groovy:85)
        at org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:90)
        at org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:143)
        at org.codenarc.rule.Rule$applyTo.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codenarc.rule.Rule$applyTo.call(Unknown Source)
        at org.codenarc.analyzer.AbstractSourceAnalyzer$_collectViolations_closure3.doCall(AbstractSourceAnalyzer.groovy:46)
        at jdk.internal.reflect.GeneratedMethodAccessor693.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.codenarc.analyzer.AbstractSourceAnalyzer.measureRuleProcessingTime(AbstractSourceAnalyzer.groovy:58)
        at jdk.internal.reflect.GeneratedMethodAccessor694.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:63)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:44)
        at org.codenarc.ant.AntFileSetSourceAnalyzer.processFile(AntFileSetSourceAnalyzer.java:188)
        at org.codenarc.ant.AntFileSetSourceAnalyzer.access$000(AntFileSetSourceAnalyzer.java:44)
        at org.codenarc.ant.AntFileSetSourceAnalyzer$1.run(AntFileSetSourceAnalyzer.java:176)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
        at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:853)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:467)
        at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1422)
        at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:230)
        at org.codehaus.groovy.control.CompilationUnit$13.call(CompilationUnit.java:700)
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:965)
        ... 39 more
```

I guess that's because CodeNarc uses [Groovy 2](https://github.com/CodeNarc/CodeNarc/blob/v2.1.0/build.gradle#L27) which doesn't support JDK 16?

**Comment by chrismair** [comment]
Yes, that is correct. Groovy 2.x does not support JDK 16. 

Until CodeNarc upgrades its configured dependency to Groovy 3.x, you should be able to override/configure the Groovy 3 dependency yourself in your build file or tool -- it depends on how you are running CodeNarc. But CodeNarc is compatible with Groovy 3.x, it just doesn't yet specify that Groovy level as its default dependency.

**Comment by boris-petrov** [comment]
What do you mean override in my build file? I’m using Gradle 7. It uses Groovy 3 by itself. How can I make it work with CodeNarc? Can you give an example on how to do that?

**Comment by erdi** [comment]
Gradle 7 indeed uses Groovy 3 but just for compiling and running build scripts. It does not necessarily use that version for compiling your project files or other things like CodeNarc analysis. You can specify which Groovy version should be used when running CodeNarc in the following way:
```
dependencies {
    codenarc('org.codenarc:CodeNarc:2.1.0')
    codenarc('org.codehaus.groovy:groovy-all:3.0.7')
}
```
Note that you need to specify a dependency on CodeNarc because a default version is used only if you don't add any dependencies to the `codenarc` dependency configuration which is added by the `codenarc` Gradle plugin.

**Comment by boris-petrov** [comment]
Thank you, that seems to have done the job!

A couple of issues I found after adding Groovy 3:

1) `SpaceAroundMapEntryColon` broke completely. No matter what parameters I give it, it fails. I used this config before:

```xml
        <rule-config name='SpaceAroundMapEntryColon'>
            <property name='characterAfterColonRegex' value='\s'/>
        </rule-config>
```

Now I had to disable the rule.

2) This suppression:

```groovy
	@SuppressWarnings('MissingBlankLineBeforeAnnotatedField')
	@Delegate
	private JerseyTest jerseyTest
```

No longer worked. I had to use `// codenarc-disable MissingBlankLineBeforeAnnotatedField` on the `jerseyTest` line. [This has been fixed since](https://github.com/CodeNarc/CodeNarc/issues/606) so maybe it doesn't really matter that much.

I searched for issues for the first one but I didn't find any relevant. Is that known? Should I open a new issue?

**Comment by chrismair** [comment]
@boris-petrov  - yes, please open a new issue for your number 1. Those tests run fine with Groovy 3.0.8 + JDK 8/11, so perhaps what you are seeing is specific to JDK 16. Please include sample code, violation info and stack trace. Thanks.

**Comment by chrismair** [comment]
Closing, as I believe the original issue has been answered/resolved. Feel free to reopen if necessary.
