### ISSUE TITLE
CodeNarc 3.0.0 against Groovy 4.0.1 codebase with @Immutable complains about AnnotationCollectorMode

### ISSUE THREAD

**Issue by merscwog** [CodeNarc/CodeNarc#680]
Excellent that CodeNarc 3.0.0 has now been released, as force running CodeNarc 2.2.0 using Groovy 3.0.9 against Groovy 4.x code kind of "worked", but the warnings and errors spit out while running were expected.  Now I'm down to just one piece of noise in the gradle build output when running CodeNarc 3.0.0 against a Groovy 4.x codebase, and it's only on classes that have used the \@Immutable annotation.

It appears that the [issue recently reported on StackOverflow](https://stackoverflow.com/questions/70779809/annotationcollectormode-cannot-be-cast-to-annotationcollectormode-in-codenarc-ta) is probably the same or very closely related to what I'm currently experiencing.  They were using CodeNarc 2.2.0 against Groovy 3.0.9 code, and received a similar stack trace to mine listed below:

```code
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[MyImmutableTestFile.groovy]]]; org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: class groovy.transform.AnnotationCollectorMode cannot be cast to class groovy.transform.AnnotationCollectorMode (groovy.transform.AnnotationCollectorMode is in unnamed module of loader java.net.URLClassLoader @7c25b060; groovy.transform.AnnotationCollectorMode is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @78b148ac)

java.lang.ClassCastException: class groovy.transform.AnnotationCollectorMode cannot be cast to class groovy.transform.AnnotationCollectorMode (groovy.transform.AnnotationCollectorMode is in unnamed module of loader java.net.URLClassLoader @7c25b060; groovy.transform.AnnotationCollectorMode is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @78b148ac)
        at org.codehaus.groovy.transform.ASTTransformationCollectorCodeVisitor.lambda$findCollectedAnnotations$1(ASTTransformationCollectorCodeVisitor.java:187)
        at java.base/java.util.Optional.map(Optional.java:260)
        at org.codehaus.groovy.transform.ASTTransformationCollectorCodeVisitor.findCollectedAnnotations(ASTTransformationCollectorCodeVisitor.java:187)
        at org.codehaus.groovy.transform.ASTTransformationCollectorCodeVisitor.visitAnnotations(ASTTransformationCollectorCodeVisitor.java:93)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:49)
        at org.codehaus.groovy.transform.ASTTransformationCollectorCodeVisitor.visitClass(ASTTransformationCollectorCodeVisitor.java:77)
        at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperations$1(ASTTransformationVisitor.java:206)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
        at org.codehaus.groovy.control.CompilationUnit$compile$2.call(Unknown Source)
        at org.codenarc.source.AbstractSourceCode.init(AbstractSourceCode.groovy:98)
        at org.codenarc.source.AbstractSourceCode.getAst(AbstractSourceCode.groovy:85)
        at org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:90)
        at org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:143)
        at org.codenarc.rule.Rule$applyTo.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codenarc.rule.Rule$applyTo.call(Unknown Source)
        at org.codenarc.analyzer.AbstractSourceAnalyzer$_collectViolations_closure3.doCall(AbstractSourceAnalyzer.groovy:46)
        at jdk.internal.reflect.GeneratedMethodAccessor1152.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.codenarc.analyzer.AbstractSourceAnalyzer.measureRuleProcessingTime(AbstractSourceAnalyzer.groovy:58)
        at jdk.internal.reflect.GeneratedMethodAccessor1151.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:192)
        at org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:44)
        at org.codenarc.ant.AntFileSetSourceAnalyzer.processFile(AntFileSetSourceAnalyzer.java:188)
        at org.codenarc.ant.AntFileSetSourceAnalyzer.access$000(AntFileSetSourceAnalyzer.java:44)
        at org.codenarc.ant.AntFileSetSourceAnalyzer$1.run(AntFileSetSourceAnalyzer.java:176)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

I still get BUILD SUCCESSFUL, and useful CodeNarc reports are generated, but it would be ideal if eventually CodeNarc 3.x could process Groovy 4.x files without warnings/errors.

**Comment by chrismair** [comment]
Hmmm, I am having trouble reproducing this. This is what I tried:
```
// build.gradle
plugins {
	id 'groovy'
	id 'codenarc'
}

repositories {
    mavenCentral()
}
     
dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.9'
}

codenarc {
	toolVersion = '3.0.0'	// also tried '2.2.0'
	configFile = file('codenarc.ruleset')
}
```
and
```
// ImmutableSample.groovy
import groovy.transform.Immutable

@Immutable
class ImmutableSample {

  private static final int COUNT = 1
}

```
and running `gradle codenarcMain` does produce violations for the ImmutableSample.groovy file, as it should.

What version of Java are you using?

**Comment by merscwog** [comment]
Probably what I should have done initially, but I've distilled the issue down to the tiniest [repository](https://github.com/merscwog/codenarc-error) that should help in reproducing what I'm seeing, although now I'm starting to second-guess why it is happening, as I've got it to fail using groovy 3.0.9 as well.

I've also given more details in the [README.md](https://github.com/merscwog/codenarc-error/blob/main/README.md) file for that sample repository. 

The RuleSet that I'm using is based upon the All Rules By Category example on the codenarc.org website, but maybe there is a rule in there that is known for triggering some issues.

Whatever I'm doing incorrectly, it does not seem to be Java version dependent.  I'm basically convinced that it's how I'm specifying the compileClasspath, but I wouldn't do that at all if it were not causing other errors without explicitly setting it.

**Comment by chrismair** [comment]
Learning the ruleset helped. I can now recreate the issue using same rulset.

The problem is with the "enhanced" rules. As a workaround you can remove (comment out) the enhanced rules from your ruleset.
 * All 4 rules under rulesets/enhanced.xml (CloneWithoutCloneable, JUnitAssertEqualsConstantActualValue, MissingOverrideAnnotation, UnsafeImplementationAsMap)
 * GrailsDomainGormMethods (although if you are not working on a Grails app you should not include any of those Grails rules)

**Comment by chrismair** [comment]
To clarify a bit ... I was able to reproduce the _original_ error referenced in your README:
```
 org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
None: 1: unable to resolve class groovy.transform.Immutable
 @ line 1, column 1.
   import groovy.transform.Immutable
   ^

None: 3: unable to resolve class groovy.transform.Immutable for annotation
 @ line 3, column 1.
   @Immutable
   ^

2 errors
```

The "enhanced" rules in CodeNarc use a deeper AST compilation. See [CodeNarc - About the Enhanced Classpath Rules](https://codenarc.org/codenarc-enhanced-classpath-rules.html).

The way we are executing the Gradle CodeNarc Plugin is not adding the necessary referenced classes (in this case @Immutable) to the classpath as the rulese are being processed.

For now at least, that probably means the "enhanced" rules need to be avoided when running through Gradle like that (until we figure out if/how that can be done).

**Comment by merscwog** [comment]
Removing the enhanced rules does indeed avoid the errors.

Explicitly setting codeNarc.compilationClasspath under gradle is the way to get the classloader conflicts:
```code
groovy.transform.AnnotationCollectorMode is in unnamed module of loader java.net.URLClassLoader @7c25b060;
groovy.transform.AnnotationCollectorMode is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @78b148ac
```

The org.gradle.internal.classloader.VisitableURLClassLoader is the interesting one, as it might be an artifact of being a gradle plugin.

Thanks for pointing out the workaround!
